language: "en"

pipeline:
  - name: "intent_featurizer_count_vectors"
  - name: "intent_classifier_tensorflow_embedding"
  - name: "ner_duckling" # pre-trained entity recognition
    dimensions: ["email"]
